### ISSUE TITLE
Adminisztrátor funkció

### ISSUE THREAD

**Issue by fulopmartin21** [CaptainCrapa/QuizBeadando#42]
Adminisztrátori frontend funkciók implementálása.

Az adminisztrátor szerepkörhöz tartozó funkciók beillesztése, ide tartozik a felhasználó saját kezű felvitele form-al,
meglévő felhasználó jelszavának módosítása, létrehozott kvízek törlése, valamint meglévő felhasználó jelszavának módosítása.

**Comment by TNorb** [comment]
@fulopmartin21 az új felhasználó felvételénél már tudjunk role-t állítani neki egyből vagy simán default diákot kapjon?

**Comment by fulopmartin21** [comment]
Tökéletes ahogy gondoltad, legyen akkor így! :)

**Comment by TNorb** [comment]
Nagyja megvan már csak a kvíz törlésének kell a backend és a role changenek szintúgy a backend kell és rá lehet húzni a frontendet.
